trigger: none

pool: 
  name: AKS
  vmImage: 'ubuntu-latest'

variables:
  AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT) # Secure variable added manually

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y jq
    chmod +x ./create-variable-groups.sh
    ./create-variable-groups.sh "$(AZURE_DEVOPS_PAT)"
  displayName: 'Create Variable Groups from JSON'
